// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nestin.Infrastructure.Data;

#nullable disable

namespace Nestin.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250414084336_SeedGuestTypesData")]
    partial class SeedGuestTypesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d35a86a5-72b3-4e7e-bb7f-5ef782b36f7c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "9c75a5df-20a4-4ff1-85a5-bb52f9cf223f",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        },
                        new
                        {
                            Id = "59ebef1f-d79b-4db0-9c5a-304836f14ff1",
                            Name = "Host",
                            NormalizedName = "HOST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nestin.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Nestin.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Åland Islands",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Algeria",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 5,
                            Name = "American Samoa",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Andorra",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Angola",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anguilla",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antarctica",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antigua and Barbuda",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Argentina",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Armenia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Aruba",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Australia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Austria",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Azerbaijan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bahamas",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bahrain",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bangladesh",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barbados",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Belarus",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Belgium",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Belize",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 24,
                            Name = "Benin",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 25,
                            Name = "Bermuda",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bhutan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bolivia",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bosnia and Herzegovina",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 29,
                            Name = "Botswana",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "Bouvet Island",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 31,
                            Name = "Brazil",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 32,
                            Name = "British Indian Ocean Territory",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 33,
                            Name = "Brunei Darussalam",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 34,
                            Name = "Bulgaria",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 35,
                            Name = "Burkina Faso",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 36,
                            Name = "Burundi",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cambodia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cameroon",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 39,
                            Name = "Canada",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cape Verde",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 41,
                            Name = "Cayman Islands",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 42,
                            Name = "Central African Republic",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chad",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chile",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 45,
                            Name = "China",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 46,
                            Name = "Christmas Island",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 47,
                            Name = "Cocos (Keeling) Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 48,
                            Name = "Colombia",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 49,
                            Name = "Comoros",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 50,
                            Name = "Congo",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 51,
                            Name = "Congo, The Democratic Republic of the",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 52,
                            Name = "Cook Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 53,
                            Name = "Costa Rica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 54,
                            Name = "Cote D'Ivoire",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 55,
                            Name = "Croatia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 56,
                            Name = "Cuba",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 57,
                            Name = "Cyprus",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 58,
                            Name = "Czech Republic",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 59,
                            Name = "Denmark",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 60,
                            Name = "Djibouti",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 61,
                            Name = "Dominica",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 62,
                            Name = "Dominican Republic",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ecuador",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 64,
                            Name = "Egypt",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 65,
                            Name = "El Salvador",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 66,
                            Name = "Equatorial Guinea",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 67,
                            Name = "Eritrea",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 68,
                            Name = "Estonia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 69,
                            Name = "Ethiopia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 70,
                            Name = "Falkland Islands (Malvinas)",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 71,
                            Name = "Faroe Islands",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 72,
                            Name = "Fiji",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 73,
                            Name = "Finland",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 74,
                            Name = "France",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 75,
                            Name = "French Guiana",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 76,
                            Name = "French Polynesia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 77,
                            Name = "French Southern Territories",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 78,
                            Name = "Gabon",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 79,
                            Name = "Gambia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 80,
                            Name = "Georgia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 81,
                            Name = "Germany",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ghana",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 83,
                            Name = "Gibraltar",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 84,
                            Name = "Greece",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 85,
                            Name = "Greenland",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 86,
                            Name = "Grenada",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 87,
                            Name = "Guadeloupe",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 88,
                            Name = "Guam",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 89,
                            Name = "Guatemala",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 90,
                            Name = "Guernsey",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 91,
                            Name = "Guinea",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 92,
                            Name = "Guinea-Bissau",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 93,
                            Name = "Guyana",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 94,
                            Name = "Haiti",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 95,
                            Name = "Heard Island and McDonald Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 96,
                            Name = "Honduras",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 97,
                            Name = "Hong Kong",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 98,
                            Name = "Hungary",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 99,
                            Name = "Iceland",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 100,
                            Name = "India",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 101,
                            Name = "Indonesia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 102,
                            Name = "Iran",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 103,
                            Name = "Iraq",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 104,
                            Name = "Ireland",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 105,
                            Name = "Israel",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 106,
                            Name = "Italy",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 107,
                            Name = "Jamaica",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 108,
                            Name = "Japan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 109,
                            Name = "Jersey",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 110,
                            Name = "Jordan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 111,
                            Name = "Kazakhstan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 112,
                            Name = "Kenya",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 113,
                            Name = "Kiribati",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 114,
                            Name = "Korea, Democratic People's Republic of",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 115,
                            Name = "Korea, Republic of",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 116,
                            Name = "Kuwait",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 117,
                            Name = "Kyrgyzstan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 118,
                            Name = "Lao People's Democratic Republic",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 119,
                            Name = "Latvia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 120,
                            Name = "Lebanon",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 121,
                            Name = "Lesotho",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 122,
                            Name = "Liberia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 123,
                            Name = "Libya",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 124,
                            Name = "Liechtenstein",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 125,
                            Name = "Lithuania",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 126,
                            Name = "Luxembourg",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 127,
                            Name = "Macao",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 128,
                            Name = "Madagascar",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 129,
                            Name = "Malawi",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 130,
                            Name = "Malaysia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 131,
                            Name = "Maldives",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 132,
                            Name = "Mali",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 133,
                            Name = "Malta",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 134,
                            Name = "Marshall Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 135,
                            Name = "Martinique",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 136,
                            Name = "Mauritania",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 137,
                            Name = "Mauritius",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 138,
                            Name = "Mayotte",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 139,
                            Name = "Mexico",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 140,
                            Name = "Micronesia (Federated States of)",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 141,
                            Name = "Moldova (Republic of)",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 142,
                            Name = "Monaco",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 143,
                            Name = "Mongolia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 144,
                            Name = "Montenegro",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 145,
                            Name = "Montserrat",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 146,
                            Name = "Morocco",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 147,
                            Name = "Mozambique",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 148,
                            Name = "Myanmar",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 149,
                            Name = "Namibia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 150,
                            Name = "Nauru",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 151,
                            Name = "Nepal",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 152,
                            Name = "Netherlands",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 153,
                            Name = "New Caledonia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 154,
                            Name = "New Zealand",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 155,
                            Name = "Nicaragua",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 156,
                            Name = "Niger",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 157,
                            Name = "Nigeria",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 158,
                            Name = "Niue",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 159,
                            Name = "Norfolk Island",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 160,
                            Name = "North Macedonia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 161,
                            Name = "Northern Mariana Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 162,
                            Name = "Norway",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 163,
                            Name = "Oman",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 164,
                            Name = "Pakistan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 165,
                            Name = "Palau",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 166,
                            Name = "Palestine",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 167,
                            Name = "Panama",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 168,
                            Name = "Papua New Guinea",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 169,
                            Name = "Paraguay",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 170,
                            Name = "Peru",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 171,
                            Name = "Philippines",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 172,
                            Name = "Pitcairn",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 173,
                            Name = "Poland",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 174,
                            Name = "Portugal",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 175,
                            Name = "Puerto Rico",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 176,
                            Name = "Qatar",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 177,
                            Name = "Romania",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 178,
                            Name = "Russian Federation",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 179,
                            Name = "Rwanda",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 180,
                            Name = "Réunion",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 181,
                            Name = "Saint Barthélemy",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 182,
                            Name = "Saint Helena, Ascension and Tristan da Cunha",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 183,
                            Name = "Saint Kitts and Nevis",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 184,
                            Name = "Saint Lucia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 185,
                            Name = "Saint Martin",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 186,
                            Name = "Saint Pierre and Miquelon",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 187,
                            Name = "Saint Vincent and the Grenadines",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 188,
                            Name = "Samoa",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 189,
                            Name = "San Marino",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 190,
                            Name = "Sao Tome and Principe",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 191,
                            Name = "Saudi Arabia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 192,
                            Name = "Senegal",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 193,
                            Name = "Serbia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 194,
                            Name = "Seychelles",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 195,
                            Name = "Sierra Leone",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 196,
                            Name = "Singapore",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 197,
                            Name = "Sint Maarten",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 198,
                            Name = "Slovakia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 199,
                            Name = "Slovenia",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 200,
                            Name = "Solomon Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 201,
                            Name = "Somalia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 202,
                            Name = "South Africa",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 203,
                            Name = "South Georgia and the South Sandwich Islands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 204,
                            Name = "South Sudan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 205,
                            Name = "Spain",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 206,
                            Name = "Sri Lanka",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 207,
                            Name = "Sudan",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 208,
                            Name = "Suriname",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 209,
                            Name = "Svalbard",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 210,
                            Name = "Swaziland",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 211,
                            Name = "Sweden",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 212,
                            Name = "Switzerland",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 213,
                            Name = "Syrian Arab Republic",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 214,
                            Name = "Taiwan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 215,
                            Name = "Tajikistan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 216,
                            Name = "Tanzania (United Republic of)",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 217,
                            Name = "Thailand",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 218,
                            Name = "Timor-Leste",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 219,
                            Name = "Togo",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 220,
                            Name = "Tokelau",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 221,
                            Name = "Tonga",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 222,
                            Name = "Trinidad and Tobago",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 223,
                            Name = "Tunisia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 224,
                            Name = "Turkey",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 225,
                            Name = "Turkmenistan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 226,
                            Name = "Tuvalu",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 227,
                            Name = "Uganda",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 228,
                            Name = "Ukraine",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 229,
                            Name = "United Arab Emirates",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 230,
                            Name = "United Kingdom of Great Britain and Northern Ireland",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 231,
                            Name = "United States of America",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 232,
                            Name = "Uruguay",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 233,
                            Name = "Uzbekistan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 234,
                            Name = "Vanuatu",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 235,
                            Name = "Venezuela (Bolivarian Republic of)",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 236,
                            Name = "Viet Nam",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 237,
                            Name = "Western Sahara",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 238,
                            Name = "Yemen",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 239,
                            Name = "Zambia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 240,
                            Name = "Zimbabwe",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 241,
                            Name = "Antarctica",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 242,
                            Name = "Ascension Island",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 243,
                            Name = "French Guiana",
                            RegionId = 5
                        });
                });

            modelBuilder.Entity("Nestin.Core.Entities.GuestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GuestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adults"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Childern"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Infants"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pets"
                        });
                });

            modelBuilder.Entity("Nestin.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 64,
                            Name = "Nazlet El-Semman, Giza Governorate"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 106,
                            Name = "Milan, Lombardia"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 191,
                            Name = "Makkah, Makkah Province"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 231,
                            Name = "Yucca Valley, California"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 31,
                            Name = "Salvador, Bahia"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 205,
                            Name = "Barcelona, Catalunya"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 110,
                            Name = "Wadi Rum Village, Aqaba Governorate"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 74,
                            Name = "Tanneron, Provence-Alpes-Côte d'Azur"
                        });
                });

            modelBuilder.Entity("Nestin.Core.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Africa & Oceania"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nestin.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nestin.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nestin.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nestin.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nestin.Core.Entities.Country", b =>
                {
                    b.HasOne("Nestin.Core.Entities.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Nestin.Core.Entities.Location", b =>
                {
                    b.HasOne("Nestin.Core.Entities.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Nestin.Core.Entities.Country", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Nestin.Core.Entities.Region", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
